name: C/C++ CI

on:
  push:
    branches: [ p-treble ]
  pull_request:
    branches: [ p-treble ]

jobs:
  build:
  steps:
    - uses: actions/checkout@v2
    - name: build
      run: build-kernel.sh
