name: C/C++ CI

on:
  push:
    branches: [ nb1-a11 ]
  pull_request:
    branches: [ nb1-a11 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./build-kernel.sh
