name: C/C++ CI

on:
  push:
    branches: [ p-treble ]
  pull_request:
    branches: [ p-treble ]

jobs:
  build:
  steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: export KBUILD_BUILD_USER="user"
export KBUILD_BUILD_HOST="build"
export ARCH="arm64"
export SUBARCH="arm64"
export TRIPLET="aarch64-none-elf-"
export TRIPLET_ARM32="arm-none-eabi-"
export CROSS_COMPILE="$(pwd)/compiler/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf/bin/$TRIPLET"
export CROSS_COMPILE_ARM32="$(pwd)/compiler/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux/gcc-arm-none-eabi-10-2020-q4-major/bin/$TRIPLET_ARM32"
export KBUILD_OUTPUT="$(pwd)/out"
export KBUILD_BUILD_USER="user"
export KBUILD_BUILD_HOST="build"
    - name: clean output dir
      run: rm -rf out
make clean && make mrproper
mkdir -p out
    - name: configure
      run: make O=out ARCH=arm64 nb1_defconfig
    - name: make
      run: make -j$(nproc --all) O=out \
    ARCH=arm64 \
    LOCALVERSION=-gcc
